"""empty message

Revision ID: a0a1bcc77ef6
Revises: d7183b2a8528
Create Date: 2023-11-23 15:54:48.249422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0a1bcc77ef6'
down_revision = 'd7183b2a8528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fullname', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_pwd', sa.String(length=120), nullable=True),
    sa.Column('user_pix', sa.String(length=120), nullable=True),
    sa.Column('user_datereg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['state_id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_author',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_author',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('user')
    # ### end Alembic commands ###
